brew "mas"
brew "terraform"
brew "tldr"
brew "delta"
brew "jq"
brew "nvim"
brew "asciinema"
brew "fzf"
brew "git"
brew "moreutils"
brew "ripgrep"
brew "xsv"
brew "gh"
brew "watch"
brew "atuin"
brew "neovim"
brew "yt-dlp"
brew "starship"
brew "weasyprint"
brew "zinit"

brew "nodenv"
brew "pyenv"
brew "go"
brew "ruff"
brew "rbenv"
brew "ruby-build"

cask "monitorcontrol"
cask "tomighty"
cask "transmission"
cask "visual-studio-code"
cask "spotify"
cask "discord"
cask "docker"
cask "1password"
cask "keepingyouawake"
cask "ngrok"
cask "cleanshot"
cask "devdocs"
cask "datagrip"
cask "slack"
cask "notion"
cask "homebrew/cask-drivers/logitech-options"
cask "linearmouse"

# Games
cask "zwift"
cask "steam"

# App Store
mas "Microsoft Remote Desktop", id: 1295203466
mas "Tailscale", id: 1475387142
mas "1Blocker: Ad Blocker & Privacy", id: 1365531024
