brew 'mas'
brew "go"
brew "nvm"
brew "rbenv"
brew "terraform"
brew "tldr"
brew "delta"
brew "jq"
brew "exa"
brew "bat"
brew "nvim"
brew "asciinema"
brew "fzf"
brew "git"
brew "moreutils"
brew "ripgrep"
brew "xsv"
brew "gh"
brew "doctl"
brew "azure-cli"
brew "google-cloud-sdk"
brew "watch"

cask "monitorcontrol"
cask "tomighty"
cask "transmission"
cask "visual-studio-code"
cask "spotify"
cask "discord"
cask "docker"
cask "1password"
cask "keepingyouawake"
cask "ngrok"
cask "cleanshot"
cask "azure-data-studio"
cask "devdocs"
cask "datagrip"
cask "slack"
cask "notion"
cask "dotnet-sdk"
cask "homebrew/cask-drivers/logitech-options"
cask "android-studio"

# Games
cask "zwift"
cask "minecraft"
cask "steam"

# App Store
mas "Microsoft Remote Desktop", id: 1295203466
mas "Tailscale", id: 1475387142
mas "1Blocker: Ad Blocker & Privacy", id: 1365531024
